[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/Maps/TestMap.TestMap
EditorStartupMap=/Game/Maps/TestMap.TestMap
GlobalDefaultGameMode=/Script/RubezhArlan.RTSGameMode

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/Engine.RendererSettings]
r.GenerateMeshDistanceFields=False
r.DynamicGlobalIlluminationMethod=0
r.ReflectionMethod=0
r.Shadow.Virtual.Enable=0
r.DefaultFeature.AutoExposure=False
r.AntiAliasingMethod=2

[/Script/NavigationSystem.NavigationSystemV1]
bAutoCreateNavigationData=True
bAllowClientSideNavigation=True

[/Script/NavigationSystem.RecastNavMesh]
CellSize=19.0
AgentRadius=40.0
AgentMaxSlope=44.0

[/Script/Engine.CollisionProfile]
; профили по умолчанию достаточно; юниты — Pawn, здания — BlockAll

[Core.Log]
LogRubezh=Log
